### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bkzutr90** [DrelezTM/StickerWhatsAppBOT#1]
~/StickerWhatsAppBOT# npm start

> stickerbot@1.2.0 start
> node .

[14:20:39] Scan the QR below :
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▄     ▀ █▀████▄▀ ▀  █    ▀█▄█ █▄▀▄ ▀██ ▄▄▄▄▄ █
█ █   █ █ ▄▄ ▀▀▄█ ▀ ▄█▄▄ ▄▀▀▄█▄▄ ▄██▄ █▀██▀▀▄▀█ █   █ █
█ █▄▄▄█ █▄  █ █ ▄██▀  ▄ █ ▄▄▄ ▀▀▄▄ █▀   ██▄ ███ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄▀ ▀▄█▄█▄█ █ █ ▀ █▄█ ▀ ▀▄█ ▀ ▀ ▀▄█ █ █▄▄▄▄▄▄▄█
█ ▄▄▄█▀▄▀    ██▄█ ▀█▀██ ▀▄ ▄▄▄▀▀ ▀▄▄ █ ▄▄ ▀▀ ▄ █▀ ▄▄█ █
██▄▀  █▄▀▀▄▄█ █ ▀▄ █▀▄▀▀ ███▄█▄ ▀ █████▀▀▀ ▄ █▄▄▀█▄▄███
█▀█▄█ █▄ █▄▄█ ▄▀ ▄  ▄ █▀ ▄▀▀█ ▄▄ █ █▄▄  ▀▀▄▄ ▀ ▄▄▄▀   █
█▀▄▀▀▀▀▄██▀▄██ █▄▄ █▀█  █ ▀█  █▄▄█▀ ▄█  ▀█▄▄▄▄ ▄█▄▀▄▀ █
█▀ ▀▀█ ▄▀▄▀  ██▄▄▀▀█ █▄▀▀▀█ █▄▀█▄▄▀▀▀▀█▄▄▀ ▄▄█ ▀▀█▀ █ █
█▄ ▄ ▀ ▄▄▄▄█▄▀█ ███▄▀   ▄█  ▀▀█  ▄▄█▄ ▄ █▀██▀▀█ █▀  ▀██
█ ▀▀█  ▄ ▄ ▄▀▄▀▀██▄██▄  ▀▀▄▄▄█  ██▄█ █ ▄█▄ ▀▀█▄▄█▀█ █▄█
█ █▄▀ █▄▀▀▄▀▄▄ ▀▄▄ █ █▀▀█▄▄█▄▀ █▀█▄▀▀▄▄█ █▀█ ▄ ▀█▄██ ██
█▄██▀ ▄▄▄ ▀█ █▄  ▀  ▀ ▀█  ▄▄▄ █▄▄█▀█ ▄▀ ▀▀▄▄▀ ▄▄▄ ▀▀▀▄█
██▀ ▄ █▄█  ▀██ ▄█▀█ ██▄█  █▄█ █▀▀▀ ▀█ ▄█  █▀█ █▄█ ▀▄ ▄█
█▄▀▀▀▄ ▄ ▄▄██▄  ▀▀ ▀█▄▄█   ▄▄▄▄▄▄  ▀▀▀▀█ ▀▀█  ▄▄ ▄▀▄███
█▀ ███ ▄█ ▄▀  ▀▀▄▀█ ▄▀█▀▀  ▄ ▄▄▀▀█ ▄▄█  ▀ ▀▄███▀▀█▄▀▄██
█▀  █▄▄▄▄█▄▄█▄ █ ▄▀█▀█▄   ██▀▀▀ ▄█▀█ ▀▀██▄ ▀▄▀▀▀█ ▀▄▀██
█▄  ▄▀▀▄   ▀▀▀▄█▄▀██▀▀█▄   ▄ ▀▀█    █ ▀ ▄█▄▀   ▀▀▀▀█▄██
██ ▄█▀█▄▀▄▀▄▄▀ ▀▀█ ▄   ▀▀ ▄█▀▀▄▄▄▀▀█▄▄▀▀▀▀▄▄▀▀█▄██▄▄ ▀█
█ █▄▀ ▄▄▄█▄▄█▀█ ▄▀  ▀█▀█▀ ███▄▀▀█ ▀ ▄▄█▀ ▀▄▄█▀  ▄█ ██▄█
██ ▀▀▀▄▄█▄▀ ██ █▀█▄█▄█ █   ▄▄▀ ▄  ▀▀█▀▄█▄█ ██▄▄▀█▄▄▄▀██
█▄ ▀▄▄▄▄ ▄▀▀█ █▀  ▄▄ █▀▀▀█ ▄ ▄█▀███▀ ▄▄▀█▄██▀█▀▀▄█   ██
████▄██▄█  ▄▄▄█▄█▄▄█ █  ▀ ▄▄▄ ▀  ██▄ █ ▄▄▄█▀▄ ▄▄▄ ▄▄▀██
█ ▄▄▄▄▄ ███▀ ▀ ▄█▄█  ▄█ ▀ █▄█ █▀ ▀▀▀▀▀▀▄█ █ ▄ █▄█ █▄▄██
█ █   █ █▀▀█ █▀███ █▀▀███ ▄ ▄▄▄▄▄█ ▄▀ ▀ ███▄█     ▄█▀██
█ █▄▄▄█ █ █████▀ ▄▄▄▄▀▀ ▄▀▀▄▄ ▄▀▀▀█ ▀▄█▀▀▀▀▀█▀▄█▄█ ▄ ██
█▄▄▄▄▄▄▄█▄▄▄▄▄███▄██▄█████▄█▄██▄█▄▄█▄██▄▄██▄██▄███▄█▄██

/root/StickerWhatsAppBOT/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
    at __puppeteer_evaluation_script__:14:123
    at ExecutionContext._evaluateInternal (/root/StickerWhatsAppBOT/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/root/StickerWhatsAppBOT/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.initialize (/root/StickerWhatsAppBOT/node_modules/whatsapp-web.js/src/Client.js:267:9)
root@iZt4n399yyn07pki1eijsdZ:~/StickerWhatsAppBOT#

**Comment by NikitoDev** [comment]
I have the same error, any solution? 😢

**Comment by DrelezTM** [comment]
open file
```
/node_modules/whatsapp-web.js/src/util/Injected.js
```
change line 17 of Injected.js from:
```js
window.Store.GroupMetadata = window.mR.findModule((module) => module.default && module.default.handlePendingInvite)[0].default;
```
to:
```js
window.Store.GroupMetadata = window.mR.findModule('GroupMetadata')[0].default.GroupMetadata;
```
issues: https://github.com/pedroslopez/whatsapp-web.js/issues/1786
