### ISSUE TITLE
Can you tell me whats this problem and how can i fix it?

### ISSUE THREAD

**Issue by manjisama1** [DrelezTM/StickerWhatsAppBOT#10]
![Uploading Screenshot_2024-04-16-19-21-57-06_84d3000e3f4017145260f7618db1d683.jpg…]()

Node.js v21.6.2
npm ERR! code 1
npm ERR! path /data/data/com.termux/files/home/StickerWhatsAppBOT/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js

npm ERR! A complete log of this run can be found in: /data/data/com.termux/files/home/.npm/_logs/2024-04-16T13_51_18_249Z-debug-0.log

**Comment by DrelezTM** [comment]
StickerWhatsAppBOT does not support Termux/Android because it uses Puppeteer
https://github.com/DrelezTM/StickerWhatsAppBOT?tab=readme-ov-file#warning-
