### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yekayee** [DrelezTM/StickerWhatsAppBOT#6]
after scans, stuck in qr, not happened after scans

**Comment by DrelezTM** [comment]
use whatsapp-web.js v1.21.1-alpha.1 or you can [install the latest version of StickerWhatsAppBOT](https://github.com/DrelezTM/StickerWhatsAppBOT/commit/9620395abbb257c8a61a6daa701d3eed8573aa0e)

- open file `/node_modules/whatsapp-web.js/src/Client.js`
- replace this:
  ```js
  const INTRO_IMG_SELECTOR = '[data-testid="intro-md-beta-logo-dark"], [data-testid="intro-md-beta-logo-light"], [data-asset-intro-image-light="true"], [data-asset-intro-image-dark="true"]';
  ```
- into this:
  ```js
  const INTRO_IMG_SELECTOR = "[data-icon='chat']";
  ```

**source** : https://github.com/pedroslopez/whatsapp-web.js/issues/2422
